activityScheduleAssigner: standard
carOwnership:
  engine: config/leopoldshafen/parameters/SociodemographicCoefficients.txt
  ownership: config/leopoldshafen/parameters/CarOwnershipModelParameter.txt
  segment: config/leopoldshafen/parameters/LogitBasedCarSegmentModelParameter.txt
#mobilityProviders:
commuterTicket: config/leopoldshafen/parameters/TransitPassParameter.txt
dataSource: !file
  demandDataFolder: output/demand-data
  matrixConfigurationFile: data/leopoldshafen/matrices/matrix-configuration.yaml
  attractivityDataFile: data/leopoldshafen/zoneproperties/attractivities.csv
  zonePropertiesDataFile: data/leopoldshafen/zoneproperties/zone-properties.csv
  parkingFacilitiesDataFile: data/leopoldshafen/zoneproperties/parkingFacilities.csv
  bikeSharingPropertiesDataFile: data/leopoldshafen/zoneproperties/bikesharing-properties.csv
  carSharingPropertiesDataFile: data/leopoldshafen/zoneproperties/carsharing-properties.csv
  carSharingStationsDataFile: data/leopoldshafen/zoneproperties/carsharing-stations.csv
  carSharingFreeFloatingDataFile: data/leopoldshafen/zoneproperties/carsharing-free-floating.csv
  #charging: unlimited
  defaultChargingPower: config/leopoldshafen/parameters/ChargingPower.txt
  zoneRepositoryFolder: output/zone-repository/
demographyData: 
  age_f: data/leopoldshafen/leopoldshafen-Demography-ipf.csv
  age_m: data/leopoldshafen/leopoldshafen-Demography-ipf.csv
  dom_code: data/leopoldshafen/leopoldshafen-Demography-ipf.csv
  job: data/leopoldshafen/leopoldshafen-Demography-ipf.csv
#numberOfZones: 2147483647
panelData: data/leopoldshafen/population.csv
resultFolder: results/population-synthesis
seed: 77859
synthesisZoneProperties: data/leopoldshafen/zoneproperties/synthesis-zone-properties.csv
visumFile: data/leopoldshafen/leopoldshafen.net
#experimental:
#  parameter1: 1
#  parameter2: 2
