costMatrices:
  car:
    at:
      weekdays:
        between:
          0 to 23: cost.car.mtx
      saturday:
        between:
          0 to 23: cost.car.mtx
      sunday:
        between:
          0 to 23: cost.car.mtx
  constant:
    at:
      weekdays:
        between:
          0 to 23: cost.car.mtx
      saturday:
        between:
          0 to 23: cost.car.mtx
      sunday:
        between:
          0 to 23: cost.car.mtx
  parkingstress:
    at:
      weekdays:
        between:
          0 to 23: cost.car.mtx
      saturday:
        between:
          0 to 23: cost.car.mtx
      sunday:
        between:
          0 to 23: cost.car.mtx
  distance:
    at:
      weekdays:
        between:
          0 to 23: distance.car.mtx
      saturday:
        between:
          0 to 23: distance.car.mtx
      sunday:
        between:
          0 to 23: distance.car.mtx
  parking:
    at:
      weekdays:
        between:
          0 to 23: cost.car.mtx
      saturday:
        between:
          0 to 23: cost.car.mtx
      sunday:
        between:
          0 to 23: cost.car.mtx
  publictransport:
    at:
      weekdays:
        between:
          0 to 23: cost.pt.mtx
      saturday:
        between:
          0 to 23: cost.pt.mtx
      sunday:
        between:
          0 to 23: cost.pt.mtx
fixedDistributionMatrices:
  EDUCATION_PRIMARY: distribution.work.mtx
  EDUCATION_TERTIARY: distribution.work.mtx
  EDUCATION_OCCUP: distribution.work.mtx
  EDUCATION_SECONDARY: distribution.work.mtx
  EDUCATION: distribution.work.mtx
  WORK: distribution.work.mtx
travelTimeMatrices:
  pedestrian:
    at:
      weekdays:
        between:
          0 to 23: traveltime.bike.mtx
      saturday:
        between:
          0 to 23: traveltime.bike.mtx
      sunday:
        between:
          0 to 23: traveltime.bike.mtx
  car:
    at:
      weekdays:
        between:
          0 to 23: traveltime.car.mtx
      saturday:
        between:
          0 to 23: traveltime.car.mtx
      sunday:
        between:
          0 to 23: traveltime.car.mtx
  publictransport:
    at:
      weekdays:
        between:
          0 to 23: traveltime.put.mtx
      saturday:
        between:
          0 to 23: traveltime.put.mtx
      sunday:
        between:
          0 to 23: traveltime.put.mtx
  bike:
    at:
      weekdays:
        between:
          0 to 23: traveltime.bike.mtx
      saturday:
        between:
          0 to 23: traveltime.bike.mtx
      sunday:
        between:
          0 to 23: traveltime.bike.mtx
